# ENV は eval することで値を取得する
# id = yaml["basic_attributes"]["id"]; eval(id);
# したがって、文字列を直書きするときはクォートしないとエラーになるので注意する

basic_attributes:
  id: ENV.fetch('SPREADSHEET_ID_BASIC_ATTRIBUTES')
  worksheet_names:
    - stars
    - companies
    - game_platforms
    - tax_rates

products:
  id: ENV.fetch('SPREADSHEET_ID_PRODUCTS')
  worksheet_names:
    - titles

characters:
  id: ENV.fetch('SPREADSHEET_ID_CHARACTERS')
  worksheet_names:
    - bases
