# ENV は eval することで値を取得する
# id = yaml["basic_attributes"]["id"]; eval(id);
# したがって、変数であってもクォートしないとエラーになるので注意する（イケてないので直したい）

basic_attributes:
  id: ENV.fetch('SPREADSHEET_ID_BASIC_ATTRIBUTES')
  worksheet_names:
    - stars
    - water_margin_characters
    - companies
    - platforms
    - tax_rates

products:
  id: ENV.fetch('SPREADSHEET_ID_PRODUCTS')
  worksheet_names:
    - titles

characters:
  id: ENV.fetch('SPREADSHEET_ID_CHARACTERS')
  worksheet_names:
    - bases

gss_hq_characters_section:
  id: ENV.fetch('SPREADSHEET_ID_GSS_HQ_CHARACTERS_SECTION')
  worksheet_names:
    - web_format_data

gss_cities_section:
  id: ENV.fetch('SPREADSHEET_ID_GSS_CITIES_SECTION')
  worksheet_names:
    - web_format_data

gss_character:
  id: ENV.fetch('SPREADSHEET_ID_GSS_CHARACTER')
  worksheet_names:
    - web_format_data
    - DB_nicknames
