default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suikoden_vault_development

test:
  <<: *default
  database: suikoden_vault_test

production:
  <<: *default
  database: suikoden_vault_production
  username: vault
  password: <%= ENV["SUIKODEN_VAULT_DATABASE_PASSWORD"] %>
