default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: suikoden_vault_development
  host: <%= ENV.fetch('PG_DEVELOPMENT_HOST') || 'localhost' %>
  port: <%= ENV.fetch('PG_DEVELOPMENT_PORT') || 5432 %>
  username: <%= ENV.fetch('PG_DEVELOPMENT_USER') || 'root' %>
  password: <%= ENV.fetch('PG_DEVELOPMENT_PASS') || 'postgres' %>

test:
  <<: *default
  database: suikoden_vault_test
  host: <%= ENV.fetch('PG_TEST_HOST') || 'localhost' %>
  port: <%= ENV.fetch('PG_TEST_PORT') || 5432 %>
  username: <%= ENV.fetch('PG_TEST_USER') || 'root' %>
  password: <%= ENV.fetch('PG_TEST_PASS') || 'postgres' %>

production:
  <<: *default
  database: suikoden_vault_production
  host: <%= ENV.fetch('PG_PRODUCTION_HOST') || 'localhost' %>
  port: <%= ENV.fetch('PG_PRODUCTION_PORT') || 5432 %>
  username: <%= ENV.fetch('PG_PRODUCTION_USER') %>
  password: <%= ENV.fetch('PG_PRODUCTION_PASS') %>
  sslmode: verify-ca
  sslcert: <%= ENV.fetch('PG_SSLCERT_PATH') || 'config/postgresql/client.crt' %>
  sslkey: <%= ENV.fetch('PG_SSLKEY_PATH') || 'config/postgresql/client.key' %>
  sslrootcert: <%= ENV.fetch('PG_SSLROOT_PATH') || 'config/postgresql/root.crt' %>
